### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by T1MOXA** [robingrether/iDisguise#10]
```
[Craft Scheduler Thread - 464/ERROR]: [iDisguise] Cannot retrieve the required profile information.
java.io.IOException: Server returned HTTP response code: 429 for URL: https://sessionserver.mojang.com/session/minecraft/profile/4ced2967751d4dc4843c5fc2a14fe495?unsigned=false
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_111]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_111]
	at de.robingrether.idisguise.management.player.PlayerHelperUID18.loadGameProfile(PlayerHelperUID18.java:109) [idisguise-full-5.6.4-20170619.181215-4.jar:?]
	at de.robingrether.idisguise.management.player.PlayerHelperUID18.loadGameProfile(PlayerHelperUID18.java:73) [idisguise-full-5.6.4-20170619.181215-4.jar:?]
	at de.robingrether.idisguise.management.player.PlayerHelperUID18.access$1(PlayerHelperUID18.java:50) [idisguise-full-5.6.4-20170619.181215-4.jar:?]
	at de.robingrether.idisguise.management.player.PlayerHelperUID18$1.run(PlayerHelperUID18.java:196) [idisguise-full-5.6.4-20170619.181215-4.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-b78586d-f3356f1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by luisagrether** [comment]
Do you use any plugin that loads player skins from Mojang's server?

**Comment by T1MOXA** [comment]
Yes, https://www.spigotmc.org/resources/skinsrestorer.2124/

**Comment by luisagrether** [comment]
Ok, then I will have to recode skin loading in my plugin...

I'll send you a message as soon as a snapshot is available

**Comment by luisagrether** [comment]
Finally, after recoding this part of my plugin for like 10,000 times :D 

Version 5.6.4 snapshot #16 (or higher) should solve the problem. You can grab it over here: https://www.robingrether.de/idisguise/
