### ISSUE TITLE
Error shuting down server

### ISSUE THREAD

**Issue by Oxykronnos** [robingrether/iDisguise#12]
Hey, when i shut down my server i get this error:

```
[18:03:41] [Craft Scheduler Thread - 102/ERROR]: [iDisguise] Cannot retrieve the required profile information.
java.io.IOException: Server returned HTTP response code: 429 for URL: https://sessionserver.mojang.com/session/minecraft/profile/545fee25b3394e4cb4aa749f0c1eb293?unsigned=false
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_111]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_111]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_111]
at de.robingrether.idisguise.management.player.PlayerHelperUID18.loadGameProfile(PlayerHelperUID18.java:106) [iDisguise.jar:?]
at de.robingrether.idisguise.management.player.PlayerHelperUID18.access$2(PlayerHelperUID18.java:89) [iDisguise.jar:?]
at de.robingrether.idisguise.management.player.PlayerHelperUID18$2.run(PlayerHelperUID18.java:206) [iDisguise.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

I've a lot of plugins btw.

**Comment by Oxykronnos** [comment]
Version 1.12, it just throw this error randomly. Now i can see i don't need to shut down, it just happens:

`[06:03:29] [Craft Scheduler Thread - 11/ERROR]: [iDisguise] Cannot retrieve the required profile information.
java.io.IOException: Server returned HTTP response code: 429 for URL: https://sessionserver.mojang.com/session/minecraft/profile/545fee25b3394e4cb4aa749f0c1eb293?unsigned=false
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[?:1.8.0_111]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_111]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_111]
at de.robingrether.idisguise.management.player.PlayerHelperUID18.loadGameProfile(PlayerHelperUID18.java:106) [iDisguise.jar:?]
at de.robingrether.idisguise.management.player.PlayerHelperUID18.access$2(PlayerHelperUID18.java:89) [iDisguise.jar:?]
at de.robingrether.idisguise.management.player.PlayerHelperUID18$2.run(PlayerHelperUID18.java:206) [iDisguise.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by luisagrether** [comment]
This bug has been fixed already. You may go and download 5.6.4 snapshot #13 which contains the bugfix.

You can download snapshots over here: https://www.robingrether.de/idisguise/

**Comment by Oxykronnos** [comment]
You just rock man!

**Comment by luisagrether** [comment]
Finally, you may switch to the official release (5.6.4) which contains the bugfix as well.

https://www.spigotmc.org/resources/idisguise.5509/
