### ISSUE TITLE
Incompatible with Spigot 1.13.2?

### ISSUE THREAD

**Issue by DanielMalmgren** [robingrether/iDisguise#27]
I get the following when trying iDisguise with Spigot 1.13.2:

```
[19:47:26] [Server thread/INFO]: [iDisguise] Enabling iDisguise v5.8.1
[19:47:26] [Server thread/ERROR]: [iDisguise] Cannot parse line: Block_fromLegacyData->MBlock$fromLegacyData(int)
java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.Block.fromLegacyData(int)
        at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_171]
        at de.robingrether.idisguise.management.Reflection.load(Reflection.java:469) ~[?:?]
        at de.robingrether.idisguise.management.VersionHelper.init(VersionHelper.java:91) ~[?:?]
        at de.robingrether.idisguise.iDisguise.onEnable(iDisguise.java:73) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:804) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.Bukkit.reload(Bukkit.java:569) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[19:47:26] [Server thread/ERROR]: [iDisguise] Cannot parse line: Block_getById->MBlock$getById(int)
java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.Block.getById(int)
        at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_171]
        at de.robingrether.idisguise.management.Reflection.load(Reflection.java:469) ~[?:?]
        at de.robingrether.idisguise.management.VersionHelper.init(VersionHelper.java:91) ~[?:?]
        at de.robingrether.idisguise.iDisguise.onEnable(iDisguise.java:73) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:804) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.Bukkit.reload(Bukkit.java:569) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[19:47:26] [Server thread/ERROR]: [iDisguise] Cannot parse line: Entity_setCustomName->MEntity$setCustomName(java.lang.String)
java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.Entity.setCustomName(java.lang.String)
        at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_171]
        at de.robingrether.idisguise.management.Reflection.load(Reflection.java:469) ~[?:?]
        at de.robingrether.idisguise.management.VersionHelper.init(VersionHelper.java:91) ~[?:?]
        at de.robingrether.idisguise.iDisguise.onEnable(iDisguise.java:73) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:804) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.Bukkit.reload(Bukkit.java:569) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[19:47:26] [Server thread/ERROR]: [iDisguise] Cannot parse line: PacketPlayInUseEntity_getAction->MPacketPlayInUseEntity$a()
java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a()
        at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_171]
        at de.robingrether.idisguise.management.Reflection.load(Reflection.java:469) ~[?:?]
        at de.robingrether.idisguise.management.VersionHelper.init(VersionHelper.java:91) ~[?:?]
        at de.robingrether.idisguise.iDisguise.onEnable(iDisguise.java:73) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:804) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.Bukkit.reload(Bukkit.java:569) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[19:47:26] [Server thread/ERROR]: [iDisguise] An unexpected exception occured.
java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_171]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72) ~[?:1.8.0_171]
        at de.robingrether.idisguise.management.Reflection.load(Reflection.java:439) ~[?:?]
        at de.robingrether.idisguise.management.VersionHelper.init(VersionHelper.java:92) ~[?:?]
        at de.robingrether.idisguise.iDisguise.onEnable(iDisguise.java:73) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:804) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.Bukkit.reload(Bukkit.java:569) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-eb21557-4a47be6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[19:47:26] [Server thread/ERROR]: [iDisguise] iDisguise 5.8.1 is not compatible with your server version!
[19:47:26] [Server thread/INFO]: [iDisguise] Disabling iDisguise v5.8.1
```

**Comment by robingrether** [comment]
I've tried to reprocude this issue on my local server:
Neither Java 10 nor Java 8_181 generate this error. (I've tested the same Spigot build _git-Spigot-eb21557-4a47be6_)

**Comment by robingrether** [comment]
Theoretically it could be Java 8_171 causing the issue. However, I don't think so...

**Comment by luisagrether** [comment]
Where did you download iDisguise 5.8.1?

The error log does not fit the code of iDisguise 5.8.1...

**Comment by DanielMalmgren** [comment]
I used the download link here: [https://www.spigotmc.org/resources/idisguise.5509/](url)

Using openjdk 1.8.0_171 on a Debian Jessie server.

**Comment by robingrether** [comment]
That's weird...

Just for you to understand what I mean:

When you start iDisguise, it loads reflection settings from a few .txt files inside the jar file. In the first four error logs the exception occurs in line 91 of [de.robingrether.idisguise.management.VersionHelper](https://github.com/robingrether/iDisguise/blob/7889e766c77465e042e05d300d6ae963ca26dd63/idisguise-core/src/main/java/de/robingrether/idisguise/management/VersionHelper.java). This is where it loads the file "[reflection/common.txt](https://github.com/robingrether/iDisguise/blob/7889e766c77465e042e05d300d6ae963ca26dd63/idisguise-core/src/main/resources/de/robingrether/idisguise/management/reflection/common.txt)". The weird thing is that the four reflection info lines that cannot be interpreted properly (because the associated functions don't exist in Spigot 1.13.2) don't exist in that file.... thus the first four exceptions should actually not occur.

The last exception occurs in line 92 of [de.robingrether.idisguise.management.VersionHelper](https://github.com/robingrether/iDisguise/blob/7889e766c77465e042e05d300d6ae963ca26dd63/idisguise-core/src/main/java/de/robingrether/idisguise/management/VersionHelper.java). This is where iDisguise loads the version specific reflection info. As you are running Spigot 1.13.2, it should load the file "[reflection/v1_13_R2.txt](https://github.com/robingrether/iDisguise/blob/7889e766c77465e042e05d300d6ae963ca26dd63/idisguise-core/src/main/resources/de/robingrether/idisguise/management/reflection/v1_13_R2.txt)". The weird thing here is that the NullPointerException, which occurs, implies that the file could either not be found or is empty which isn't the case.... thus this exception should actually not occur either.

I've got no plan what's wrong here... as the behavior does not match the code and resources ...

**Comment by luisagrether** [comment]
Well, it seems like the jar file you downloaded is somehow corrupt. Please re-download the jar file and try it again...

**Comment by DanielMalmgren** [comment]
Nope. I've redownloaded and compared the files, they're identical. Could it make any difference that I've got the content of the iDisguise folder (config.yml, disguises.dat and language.yml) that I've used in earlier versions of the plugin?

**Comment by luisagrether** [comment]
Nope, the plugin folder has no influence on this.

Would you mind double-checking the file checksum against the desired value: ec0239b5a5e16a683b3d9fd1b5ddd97f (md5)

**Comment by DanielMalmgren** [comment]
Ok, this is weird. Today the error is gone and everything seems to work. I did a reload of the plugins and that didn't help but now the entire Spigot server is restarted, maybe that was needed to get rid of stuff left behind in memory from the old version of the plugin? Anyway, I guess I'll simply close this issue. Thanks for putting time into it!

**Comment by luisagrether** [comment]
Ok, thank you for the explanation. I know what's been wrong :D

This issue seemed like your jar file contained the latest code (5.8.1) but outdated resource files (5.7.x or lower) for whatever reason.
Now it's clear why... such a version mess (outdated and latest files loaded at the same time) is a typical issue when you update a plugin without a server restart.

It's good that I finally know the reason why this occurred.

**Comment by luisagrether** [comment]
Just one thing for the future... 

If you encounter a problem after updating a plugin without a server restart, you should probably first try restarting the server before reporting the issue...

**Comment by DanielMalmgren** [comment]
I'll keep that in mind ;-)
