### ISSUE TITLE
[iDisguise] Cannot retrieve the required profile information. java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by rts7771** [robingrether/iDisguise#44]
[Craft Scheduler Thread - 6/ERROR]: [iDisguise] Cannot retrieve the required profile information.
java.lang.NullPointerException: null
	at de.robingrether.idisguise.management.profile.ProfileHelperUID.loadGameProfile(ProfileHelperUID.java:122) [iDisguise.jar:?]
	at de.robingrether.idisguise.management.profile.ProfileHelperUID.loadGameProfile(ProfileHelperUID.java:76) [iDisguise.jar:?]
	at de.robingrether.idisguise.management.profile.ProfileHelperUID.access$2(ProfileHelperUID.java:52) [iDisguise.jar:?]
	at de.robingrether.idisguise.management.profile.ProfileHelperUID$3.run(ProfileHelperUID.java:219) [iDisguise.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by creekorful** [comment]
Hey there, I've fixed the issue on my fork. You can pull the source code form it and rebuild the library. It will works

**Comment by sliine** [comment]
even the new version gives this error to me

**Comment by creekorful** [comment]
> even the new version gives this error to me

even with https://github.com/creekorful/iDisguise?

**Comment by sliine** [comment]
> even with

not tested, I was going to test tomorrow, but i live in ukraine)
