### ISSUE TITLE
Cannot retrieve the required profile information.

### ISSUE THREAD

**Issue by itsWarHammer** [robingrether/iDisguise#49]
[17:43:54 ERROR]: [iDisguise] Cannot retrieve the required profile information.
java.lang.NullPointerException
        at de.robingrether.idisguise.management.profile.ProfileHelperUID.loadGameProfile(ProfileHelperUID.java:124) [idisguise-full-5.8.3-20191002.193520-3.jar:?]
        at de.robingrether.idisguise.management.profile.ProfileHelperUID.loadGameProfile(ProfileHelperUID.java:78) [idisguise-full-5.8.3-20191002.193520-3.jar:?]
        at de.robingrether.idisguise.management.profile.ProfileHelperUID.access$100(ProfileHelperUID.java:34) [idisguise-full-5.8.3-20191002.193520-3.jar:?]
        at de.robingrether.idisguise.management.profile.ProfileHelperUID$3.run(ProfileHelperUID.java:232) [idisguise-full-5.8.3-20191002.193520-3.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by itsWarHammer** [comment]
paper 1.8.8 
Version 5.8.3 SNAPSHOT
