### ISSUE TITLE
Minecraft 1.12-pre2

### ISSUE THREAD

**Issue by ghost** [robingrether/iDisguise#6]
Hey

On latest version (Pre version released from Spigot) I'm getting http://paste.yu8.me/?cca15b1356066a81#bzzDRAZt5BEF6ZyUBU0LexaF5T0ePLsIlJDRWMuNJfU=

Just giving you a heads up before 1.12 is released

**Comment by luisagrether** [comment]
The latest snapshot will work with 1.12 for the most part. You can grab it here: https://www.robingrether.de/idisguise/

However parrots are not supported yet.

**Comment by dyanakiev** [comment]
Im using the latest snapshot and here is error when player is joining the server:
```
 [iDisguise] Cannot retrieve the required profile information.
java.lang.NullPointerException: null
        at java.io.StringReader.<init>(Unknown Source) ~[?:1.8.0_131]
        at org.json.simple.JSONValue.parse(JSONValue.java:50) ~[server.jar:?]
        at de.robingrether.idisguise.management.player.PlayerHelperUID18.loadGameProfile(PlayerHelperUID18.java:63) [idisguise-full-5.6.3-20170603.105315-12.jar:?]
        at de.robingrether.idisguise.management.player.PlayerHelperUID18.access$1(PlayerHelperUID18.java:43) [idisguise-full-5.6.3-20170603.105315-12.jar:?]
        at de.robingrether.idisguise.management.player.PlayerHelperUID18$1.run(PlayerHelperUID18.java:183) [idisguise-full-5.6.3-20170603.105315-12.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.12-pre6.jar:git-Paper-"04d2d385"]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12-pre6.jar:git-Paper-"04d2d385"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12-pre6.jar:git-Paper-"04d2d385"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

The plugin is working anyway.

**Comment by luisagrether** [comment]
Are you running your server in offline mode? If yes, this triggers the error.

I've recently reworked loading skin data and at the moment offline mode is not supported entirely. This will be fixed in the next snapshot.

**Comment by luisagrether** [comment]
Snapshot #14 should finally fix all problems with offline mode :)

https://www.robingrether.de/idisguise/

**Comment by luisagrether** [comment]
Release version 5.6.3 should finally fix the problems as well. And of course, it provides full support for Minecraft 1.12.

https://www.spigotmc.org/resources/idisguise.5509/
